### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by liufuyan2016** [ruanjue/wtdbg-2.huge#1]
Dear,
How to install the soft and which version of gcc used? Thank you a lot !

**Comment by ruanjue** [comment]
This is a intermediate version, please use wtdbg2 https://github.com/ruanjue/wtdbg2

**Comment by liufuyan2016** [comment]
Does the version 2  could be used for larger genome assembly? I see the African lungfish genome use this version

**Comment by ruanjue** [comment]
Yes, wtdbg2 inherit all the features to assemble huge genomes.
